;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Archer.ChargedShot",DevComment="")
+GameplayTagList=(Tag="Ability.Archer.Dodge",DevComment="")
+GameplayTagList=(Tag="Ability.Archer.FanShot",DevComment="")
+GameplayTagList=(Tag="Ability.Archer.LightAttack",DevComment="")
+GameplayTagList=(Tag="Ability.Archer.RapidFire",DevComment="")
+GameplayTagList=(Tag="Ability.Archer.VolleyShot",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Ranged",DevComment="")
+GameplayTagList=(Tag="Ability.Mobility",DevComment="")
+GameplayTagList=(Tag="Ability.Special",DevComment="")
+GameplayTagList=(Tag="Ability.Test.Basic",DevComment="")
+GameplayTagList=(Tag="Ability.Test.FollowUp",DevComment="")
+GameplayTagList=(Tag="Ability.Warrior.SwordSlash",DevComment="")
+GameplayTagList=(Tag="Event.Ability.EarlyCancellation.Close",DevComment="")
+GameplayTagList=(Tag="Event.Ability.EndSwordTrace",DevComment="")
+GameplayTagList=(Tag="Event.Ability.InputCheckPoint",DevComment="")
+GameplayTagList=(Tag="Event.Ability.StartSwordTrace",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Test.Action",DevComment="")
+GameplayTagList=(Tag="Event.Ability.Transition.Open",DevComment="")
+GameplayTagList=(Tag="Event.Archery.NockArrow",DevComment="")
+GameplayTagList=(Tag="Event.Archery.ReleaseArrow",DevComment="")
+GameplayTagList=(Tag="Event.Archery.SpawnArrow",DevComment="")
+GameplayTagList=(Tag="Input.Ability.ChargedShot",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Dodge",DevComment="")
+GameplayTagList=(Tag="Input.Ability.FanShot",DevComment="")
+GameplayTagList=(Tag="Input.Ability.Primary",DevComment="")
+GameplayTagList=(Tag="Input.Ability.VolleyShot",DevComment="")

