// AbilitySystemTags.h
#pragma once

#include "NativeGameplayTags.h"

namespace AbilitySystemTags
{
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Invulnerable);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Damage);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_DamageTaken);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Cost);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Cooldown);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_ProjectileCount);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_ShotCount);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_ChargeTime);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Spread);
	ABILITYSYSTEM_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Radius);
}